env: flex
runtime: nodejs

env_variables:
  SQL_USER: citizen
  SQL_PASSWORD: civic.MIND
  SQL_DATABASE: results
  INSTANCE_CONNECTION_NAME: citizenslikeme:us-west1:citizen-discourse

beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: citizenslikeme:us-west1:citizen-discourse
